const SOCKET_EVENT = {
  SET_USER_ID: 'SET_USER_ID',
  PRIVATE_CHAT: 'PRIVATE_CHAT',
  SEND_MESSAGE_PRIVATE: 'SEND_MESSAGE_PRIVATE',
  GROUP_CHAT: 'GROUP_CHAT',
  USER_LOGOUT: 'USER_LOGOUT',
  SEND_MESSAGE_GROUP_START: 'SEND_MESSAGE_GROUP_START',
  SEND_MESSAGE_GROUP_COMPLETED: 'SEND_MESSAGE_GROUP_COMPLETED',
  CREATE_GROUP_CHAT_START: 'CREATE_GROUP_CHAT_START',
  CREATE_GROUP_CHAT_COMPLETED: 'CREATE_GROUP_CHAT_COMPLETED',
}
module.exports = {
  SOCKET_EVENT,
}
