const SOCKET_EVENT = {
  SEND_MESSAGE: 'SEND_MESSAGE',
  SET_USER_ID: 'SET_USER_ID',
  PRIVATE_CHAT: 'PRIVATE_CHAT',
  SEND_MESSAGE_PRIVATE: 'SEND_MESSAGE_PRIVATE',
}
module.exports = {
  SOCKET_EVENT,
}
